# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Integrated Physical Chemistry
author: "Nicole M. James"
logo: ""
copyright: "2026"

# https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinx_tippy
  config:
    tippy_enable_mathjax: true
    templates_path: ["_templates"]
    html_static_path: ["_static"]
    html_js_files:
      - "collapse_footnotes.js"
      - "custom.js"
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
      - "https://unpkg.com/@jupyter-widgets/html-manager@^0.20.1/dist/embed-amd.js"
    html_css_files:
      - "https://unpkg.com/tippy.js@6/themes/light-border.css"
    tippy_props:
      placement: "top"
      interactive: true
      theme: "light-border"
    tippy_skip_anchor_classes:
      - "headerlink"
      - "sd-stretched-link"
      - "exercise"
      - "solution"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


bibtex_bibfiles:
  - references.bib 

repository:
  url: https://github.com/nicolemjames/integrated-pchem  
  branch: main

html:
  use_issues_button: false
  use_repository_button: false
  css_files:
    - _static/custom.css

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true
