# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Integrated Physical Chemistry
author: Nicole M. James
logo: ""
copyright: "2026"

# https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

sphinx:
  extra_extensions:
    - sphinx_exercise
    - hoverxref.extension
  config:
    hoverxref_auto_ref: true
    hoverxref_domains:
      - std
    hoverxref_roles:
      - term
      - ref
      - doc
      - cite
      - numref
    hoverxref_role_types:
      term: tooltip       
      ref: tooltip
      doc: tooltip
      cite: tooltip
      numref: tooltip
    hoverxref_mathjax: true 

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


bibtex_bibfiles:
  - references.bib 

repository:
  url: https://github.com/nicolemjames/integrated-pchem  
  branch: main

html:
  use_issues_button: false
  use_repository_button: false

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true
